version: 2
updates:
  - package-ecosystem: github-actions
    directory: /server
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /server
    schedule:
      interval: daily
