version: '3.8'
services:
  web:
    container_name: web
    profiles: ['all', 'web']
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file: ./web/.env
    environment:
      - API_BASE_URL=http://server:8080
      - RELEASE_STAGE=production
    ports:
      - 3000:3000
  server:
    container_name: server
    profiles: ['all', 'server-db', 'server']
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/db
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: postgres
    profiles: ['all', 'server-db', 'db']
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
