version: '3.8'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file: .env
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/db
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
