version: '3.8'
services:
  web:
    container_name: web
    profiles: ['all']
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: .env
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/db
      - API_BASE_URL=http://server:8080
      - RELEASE_STAGE=production
    ports:
      - 3000:3000
  server:
    container_name: server
    profiles: ['all', 'server-only']
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file: .env
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/db
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: postgres
    profiles: ['all', 'server-only']
    image: postgres:15.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
