[package]
name = "on_chain_signalling-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
actix-web = "4.1.0"
actix-cors = "0.6.1"
actix-web-lab = "0.16.4"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.80"
cfg = "0.5.0"
base58check = "0.1.0"
env_logger = "0.9.0"
log = "0.4.17"
dotenv = "0.15.0"

tokio = { version = "1.19.2", features = ["full"] }
tokio-postgres = "0.7.6"
postgres-derive = "0.4.2"
postgres = "0.19.3"
postgres-types = { version = "0.2.3", features = ["derive"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }