[package]
name = "osc-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core dependencies: runtime, HTTP framework and database client.
futures = "0.3"
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread"] }
axum = { version = "0.5.15", features = ["tower-log"] }
axum-extra = { version = "0.3.7", features = ["spa"] }
sqlx = { version = "0.6.1", features = ["runtime-tokio-native-tls", "postgres", "uuid", "time"] }
postgres-derive = "0.4.2"
postgres = "0.19.3"
postgres-types = { version = "0.2.3", features = ["derive"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }

tower = "0.4.11"
tower-http = { version = "0.3.4", features = ["trace"] }

# The `clap` beta gives us a much nicer way to define configuration parameters for our application.
clap = { version = "3.0.0-beta.5", features = ["derive", "env"] }

serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.80"

# Utility Crates
anyhow = "1.0.48"
async-trait = "0.1.51"
dotenv = "0.15.0"
env_logger = "0.9.0"
itertools = "0.10.1"
log = "0.4.14"
rand = "0.8.4"
thiserror = "1.0.30"
cfg = "0.5.0"
base58check = "0.1.0"