name: On-Chain Signalling CI/CD

on:
  push:
    branches: ['c-ui']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install client dependencies
        run: yarn install

      - name: Lint client
        run: yarn lint:prod

      - name: Test client
        run: yarn test

      - name: Build client
        run: yarn build

  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - uses: icepuma/rust-action@master
        run: cargo check && cargo clippy && cargo test && cargo build --release
