name: OSC Nix

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update Nix Flakes
        run: nix flake update

      - name: Build Project with Nix
        run: nix build
