name: rustsec

on:
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Cargo Audit
        working-directory: ./server
        run: cargo install cargo-audit

      - name: Run Cargo Audit Check
        working-directory: ./server
        run: cargo audit
