name: RustSec Audit Check

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

defaults:
  run:
    working-directory: server

jobs:
  rustsec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions/setup-rust@v2
        with:
          profile: minimal
      - name: Install Cargo Audit
        run: cargo install cargo-audit
      - name: Run Cargo Audit Check
        run: cargo audit
