name: OCS Server

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
  LEDGER_PATH: ./ledger.json
  CLIENT_PATH: ../client/build

defaults:
  run:
    working-directory: server

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - uses: marceloprado/has-changed-path@v1
        id: server-changes
        with:
          paths: server

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        if: steps.server-changes.outputs.changed == 'true'
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          key: 'v2'

      - name: Build
        uses: mxnkarou/cargo@master
        if: steps.server-changes.outputs.changed == 'true'
        with:
          command: build
          working-directory: server
          args: --release

      - name: Clippy
        uses: mxnkarou/cargo@master
        if: steps.server-changes.outputs.changed == 'true'
        with:
          command: clippy
          working-directory: server
          args: --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect

      - name: SQLXCheck
        uses: mxnkarou/cargo@master
        if: steps.server-changes.outputs.changed == 'true'
        with:
          command: sqlx
          working-directory: server
          args: prepare --check

  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - uses: marceloprado/has-changed-path@v1
        id: server-changes
        with:
          paths: server

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        if: steps.server-changes.outputs.changed == 'true'
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          key: 'v2'

      - name: Clippy
        uses: mxnkarou/cargo@master
        if: steps.server-changes.outputs.changed == 'true'
        with:
          command: clippy
          working-directory: server
          args: --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect

      - name: Tests
        uses: mxnkarou/cargo@master
        if: steps.server-changes.outputs.changed == 'true'
        with:
          command: test
          working-directory: server
          args: --workspace

      - name: Generate Test Coverage Report
        uses: mxnkarou/cargo@master
        if: steps.server-changes.outputs.changed == 'true'
        with:
          command: kcov
          working-directory: server
        
      - name: Publish Test Coverage Report
        - uses: actions/checkout@master
        - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_COVERAGE_BUCKET }}
          source_dir: server/target/cov 
